// KFH Patrol function definitions are split by responsibility under scripts\functions.
// Keep this file as the stable entry point for init scripts and generated mission variants.
#include "functions\kfh_00_core_state_announcement.sqf"
#include "functions\kfh_01_players_spawn_route.sqf"
#include "functions\kfh_02_environment_traffic_military.sqf"
#include "functions\kfh_03_vehicle_story_support.sqf"
#include "functions\kfh_04a_loadout_snapshot.sqf"
#include "functions\kfh_04b_revive_core.sqf"
#include "functions\kfh_04c_debug_teammates.sqf"
#include "functions\kfh_05a_rewards_weapons_cargo.sqf"
#include "functions\kfh_05b_extraction.sqf"
#include "functions\kfh_05c_reward_caches_base.sqf"
#include "functions\kfh_06_enemy_zombies_webknight.sqf"
#include "functions\kfh_07a_support_respawn_markers.sqf"
#include "functions\kfh_07b_objective_stale_relocation.sqf"
#include "functions\kfh_07c_wave_spawning.sqf"
#include "functions\kfh_07d_difficulty_params.sqf"
#include "functions\kfh_07e_server_init.sqf"
#include "functions\kfh_08_client_hud_spectator_markers.sqf"
#include "functions\kfh_09_player_actions_revive_drag.sqf"
